package org.ysu.ckqaback.qa.context;

/**
 * 持久化到 qa_retrieval_logs 的上下文与改写诊断信息。
 */
public record QaRetrievalLogContext(
        String originalQueryText,
        String retrievalQueryText,
        String standaloneQueryText,
        String contextSnapshotText,
        String contextStrategy,
        String contextMessageRange,
        int contextCharCount,
        Integer contextTokenCount,
        String contextTokenizer,
        String contextBudgetFallbackReason,
        boolean rewriteApplied,
        String rewriteReason,
        String rewriteSourceMessageRange,
        String rewriteMethod,
        String rewriteModel,
        Double rewriteConfidence,
        String contextSnapshotVersion,
        Double routingConfidence,
        String routingConfidenceBand,
        String routingReviewPriority,
        String routingSnapshotJson,
        boolean memoryApplied,
        String memoryStrategy,
        String memoryScope,
        Integer memorySourceCount,
        Integer memorySizeChars,
        Integer memoryTokenCount,
        String memoryTokenizer,
        String memoryBudgetFallbackReason,
        String memoryGovernanceVersion,
        Integer memoryLongTermCount,
        Integer memoryRecentHistoryCount,
        String memoryInjectionReason,
        String memorySourcesJson,
        String queryEngineStrategy,
        String historyFallbackReason,
        String memoryHistoryJson,
        String requestedMode,
        String resolvedMode,
        String resolvedTopic,
        String topicSource,
        Double topicConfidence,
        String topicStackJson,
        String semanticStateVersion,
        String semanticStateJson,
        Boolean topicEntityBindingApplied,
        String topicEntityBindingStatus,
        String topicEntityBindingStrategy,
        Integer topicEntityCandidateCount,
        Double topicEntityTopScore,
        String topicEntitySelectedId,
        String topicEntitySelectedName,
        String topicEntitySelectedType,
        String topicEntityCandidatesJson,
        String topicEntityFallbackReason,
        Long topicEntityLookupDurationMs
) {

    public QaRetrievalLogContext {
        semanticStateVersion = hasText(semanticStateVersion) ? semanticStateVersion : SessionSemanticState.VERSION;
        semanticStateJson = hasText(semanticStateJson)
                ? semanticStateJson
                : SessionSemanticState.fromTopicFields(
                        resolvedTopic,
                        "",
                        topicSource,
                        topicConfidence,
                        topicStackJson
                ).json();
        topicEntityBindingApplied = Boolean.TRUE.equals(topicEntityBindingApplied);
        topicEntityBindingStatus = hasText(topicEntityBindingStatus) ? topicEntityBindingStatus : "skipped";
        topicEntityBindingStrategy = hasText(topicEntityBindingStrategy) ? topicEntityBindingStrategy : "none";
        topicEntityCandidateCount = topicEntityCandidateCount == null ? 0 : Math.max(0, topicEntityCandidateCount);
        topicEntityCandidatesJson = hasText(topicEntityCandidatesJson) ? topicEntityCandidatesJson : "[]";
        topicEntityLookupDurationMs = topicEntityLookupDurationMs == null ? 0L : Math.max(0L, topicEntityLookupDurationMs);
        memoryGovernanceVersion = hasText(memoryGovernanceVersion) ? memoryGovernanceVersion : "memory-governance-v1";
        memoryLongTermCount = memoryLongTermCount == null ? 0 : Math.max(0, memoryLongTermCount);
        memoryRecentHistoryCount = memoryRecentHistoryCount == null ? 0 : Math.max(0, memoryRecentHistoryCount);
        memorySourcesJson = hasText(memorySourcesJson) ? memorySourcesJson : "[]";
    }

    public QaRetrievalLogContext(
            String originalQueryText,
            String retrievalQueryText,
            String standaloneQueryText,
            String contextSnapshotText,
            String contextStrategy,
            String contextMessageRange,
            int contextCharCount,
            boolean rewriteApplied,
            String rewriteReason,
            String rewriteSourceMessageRange,
            String rewriteMethod,
            String rewriteModel,
            Double rewriteConfidence,
            String contextSnapshotVersion,
            Double routingConfidence,
            String routingConfidenceBand,
            String routingReviewPriority,
            String routingSnapshotJson,
            boolean memoryApplied,
            String memoryStrategy,
            String memoryScope,
            Integer memorySourceCount,
            Integer memorySizeChars,
            String queryEngineStrategy,
            String historyFallbackReason,
            String memoryHistoryJson,
            String requestedMode,
            String resolvedMode,
            String resolvedTopic,
            String topicSource,
            Double topicConfidence,
            String topicStackJson
    ) {
        this(
                originalQueryText,
                retrievalQueryText,
                standaloneQueryText,
                contextSnapshotText,
                contextStrategy,
                contextMessageRange,
                contextCharCount,
                null,
                null,
                null,
                rewriteApplied,
                rewriteReason,
                rewriteSourceMessageRange,
                rewriteMethod,
                rewriteModel,
                rewriteConfidence,
                contextSnapshotVersion,
                routingConfidence,
                routingConfidenceBand,
                routingReviewPriority,
                routingSnapshotJson,
                memoryApplied,
                memoryStrategy,
                memoryScope,
                memorySourceCount,
                memorySizeChars,
                null,
                null,
                null,
                null,
                0,
                0,
                null,
                "[]",
                queryEngineStrategy,
                historyFallbackReason,
                memoryHistoryJson,
                requestedMode,
                resolvedMode,
                resolvedTopic,
                topicSource,
                topicConfidence,
                topicStackJson,
                null,
                null,
                false,
                "skipped",
                "none",
                0,
                null,
                null,
                null,
                null,
                "[]",
                "not_requested",
                0L
        );
    }

    public QaRetrievalLogContext(
            String originalQueryText,
            String retrievalQueryText,
            String standaloneQueryText,
            String contextSnapshotText,
            String contextStrategy,
            String contextMessageRange,
            int contextCharCount,
            boolean rewriteApplied,
            String rewriteReason,
            String rewriteSourceMessageRange,
            String rewriteMethod,
            String rewriteModel,
            Double rewriteConfidence,
            String contextSnapshotVersion,
            Double routingConfidence,
            String routingConfidenceBand,
            String routingReviewPriority,
            String routingSnapshotJson,
            boolean memoryApplied,
            String memoryStrategy,
            String memoryScope,
            Integer memorySourceCount,
            Integer memorySizeChars,
            String queryEngineStrategy,
            String historyFallbackReason,
            String memoryHistoryJson,
            String requestedMode,
            String resolvedMode,
            String resolvedTopic,
            String topicSource,
            Double topicConfidence,
            String topicStackJson,
            String semanticStateVersion,
            String semanticStateJson
    ) {
        this(
                originalQueryText,
                retrievalQueryText,
                standaloneQueryText,
                contextSnapshotText,
                contextStrategy,
                contextMessageRange,
                contextCharCount,
                null,
                null,
                null,
                rewriteApplied,
                rewriteReason,
                rewriteSourceMessageRange,
                rewriteMethod,
                rewriteModel,
                rewriteConfidence,
                contextSnapshotVersion,
                routingConfidence,
                routingConfidenceBand,
                routingReviewPriority,
                routingSnapshotJson,
                memoryApplied,
                memoryStrategy,
                memoryScope,
                memorySourceCount,
                memorySizeChars,
                null,
                null,
                null,
                null,
                0,
                0,
                null,
                "[]",
                queryEngineStrategy,
                historyFallbackReason,
                memoryHistoryJson,
                requestedMode,
                resolvedMode,
                resolvedTopic,
                topicSource,
                topicConfidence,
                topicStackJson,
                semanticStateVersion,
                semanticStateJson,
                false,
                "skipped",
                "none",
                0,
                null,
                null,
                null,
                null,
                "[]",
                "not_requested",
                0L
        );
    }

    public QaRetrievalLogContext(
            String originalQueryText,
            String retrievalQueryText,
            String standaloneQueryText,
            String contextSnapshotText,
            String contextStrategy,
            String contextMessageRange,
            int contextCharCount,
            boolean rewriteApplied,
            String rewriteReason,
            String rewriteSourceMessageRange,
            String rewriteMethod,
            String rewriteModel,
            Double rewriteConfidence,
            String contextSnapshotVersion,
            Double routingConfidence,
            String routingConfidenceBand,
            String routingReviewPriority,
            String routingSnapshotJson,
            boolean memoryApplied,
            String memoryStrategy,
            String memoryScope,
            Integer memorySourceCount,
            Integer memorySizeChars,
            String memoryGovernanceVersion,
            Integer memoryLongTermCount,
            Integer memoryRecentHistoryCount,
            String memoryInjectionReason,
            String memorySourcesJson,
            String queryEngineStrategy,
            String historyFallbackReason,
            String memoryHistoryJson,
            String requestedMode,
            String resolvedMode,
            String resolvedTopic,
            String topicSource,
            Double topicConfidence,
            String topicStackJson,
            String semanticStateVersion,
            String semanticStateJson
    ) {
        this(
                originalQueryText,
                retrievalQueryText,
                standaloneQueryText,
                contextSnapshotText,
                contextStrategy,
                contextMessageRange,
                contextCharCount,
                null,
                null,
                null,
                rewriteApplied,
                rewriteReason,
                rewriteSourceMessageRange,
                rewriteMethod,
                rewriteModel,
                rewriteConfidence,
                contextSnapshotVersion,
                routingConfidence,
                routingConfidenceBand,
                routingReviewPriority,
                routingSnapshotJson,
                memoryApplied,
                memoryStrategy,
                memoryScope,
                memorySourceCount,
                memorySizeChars,
                null,
                null,
                null,
                memoryGovernanceVersion,
                memoryLongTermCount,
                memoryRecentHistoryCount,
                memoryInjectionReason,
                memorySourcesJson,
                queryEngineStrategy,
                historyFallbackReason,
                memoryHistoryJson,
                requestedMode,
                resolvedMode,
                resolvedTopic,
                topicSource,
                topicConfidence,
                topicStackJson,
                semanticStateVersion,
                semanticStateJson,
                false,
                "skipped",
                "none",
                0,
                null,
                null,
                null,
                null,
                "[]",
                "not_requested",
                0L
        );
    }

    public QaRetrievalLogContext withTopicEntityBinding(QaTopicEntityBindingResult bindingResult) {
        QaTopicEntityBindingResult safeResult = bindingResult == null
                ? QaTopicEntityBindingResult.skipped("service_unavailable")
                : bindingResult;
        return new QaRetrievalLogContext(
                originalQueryText,
                retrievalQueryText,
                standaloneQueryText,
                contextSnapshotText,
                contextStrategy,
                contextMessageRange,
                contextCharCount,
                contextTokenCount,
                contextTokenizer,
                contextBudgetFallbackReason,
                rewriteApplied,
                rewriteReason,
                rewriteSourceMessageRange,
                rewriteMethod,
                rewriteModel,
                rewriteConfidence,
                contextSnapshotVersion,
                routingConfidence,
                routingConfidenceBand,
                routingReviewPriority,
                routingSnapshotJson,
                memoryApplied,
                memoryStrategy,
                memoryScope,
                memorySourceCount,
                memorySizeChars,
                memoryTokenCount,
                memoryTokenizer,
                memoryBudgetFallbackReason,
                memoryGovernanceVersion,
                memoryLongTermCount,
                memoryRecentHistoryCount,
                memoryInjectionReason,
                memorySourcesJson,
                queryEngineStrategy,
                historyFallbackReason,
                memoryHistoryJson,
                requestedMode,
                resolvedMode,
                resolvedTopic,
                topicSource,
                topicConfidence,
                topicStackJson,
                semanticStateVersion,
                semanticStateJson,
                safeResult.applied(),
                safeResult.status(),
                safeResult.strategy(),
                safeResult.candidateCount(),
                safeResult.topScore(),
                safeResult.selectedId(),
                safeResult.selectedName(),
                safeResult.selectedType(),
                safeResult.candidatesJson(),
                safeResult.fallbackReason(),
                safeResult.lookupDurationMs()
        );
    }

    public QaRetrievalLogContext withBudgetEstimates(BudgetSizeEstimate contextEstimate, BudgetSizeEstimate memoryEstimate) {
        return new QaRetrievalLogContext(
                originalQueryText,
                retrievalQueryText,
                standaloneQueryText,
                contextSnapshotText,
                contextStrategy,
                contextMessageRange,
                contextCharCount,
                estimateTokens(contextEstimate),
                estimateTokenizer(contextEstimate),
                estimateFallbackReason(contextEstimate),
                rewriteApplied,
                rewriteReason,
                rewriteSourceMessageRange,
                rewriteMethod,
                rewriteModel,
                rewriteConfidence,
                contextSnapshotVersion,
                routingConfidence,
                routingConfidenceBand,
                routingReviewPriority,
                routingSnapshotJson,
                memoryApplied,
                memoryStrategy,
                memoryScope,
                memorySourceCount,
                memorySizeChars,
                estimateTokens(memoryEstimate),
                estimateTokenizer(memoryEstimate),
                estimateFallbackReason(memoryEstimate),
                memoryGovernanceVersion,
                memoryLongTermCount,
                memoryRecentHistoryCount,
                memoryInjectionReason,
                memorySourcesJson,
                queryEngineStrategy,
                historyFallbackReason,
                memoryHistoryJson,
                requestedMode,
                resolvedMode,
                resolvedTopic,
                topicSource,
                topicConfidence,
                topicStackJson,
                semanticStateVersion,
                semanticStateJson,
                topicEntityBindingApplied,
                topicEntityBindingStatus,
                topicEntityBindingStrategy,
                topicEntityCandidateCount,
                topicEntityTopScore,
                topicEntitySelectedId,
                topicEntitySelectedName,
                topicEntitySelectedType,
                topicEntityCandidatesJson,
                topicEntityFallbackReason,
                topicEntityLookupDurationMs
        );
    }

    private static Integer estimateTokens(BudgetSizeEstimate estimate) {
        return estimate == null ? null : estimate.tokens();
    }

    private static String estimateTokenizer(BudgetSizeEstimate estimate) {
        return estimate == null ? null : estimate.tokenizer();
    }

    private static String estimateFallbackReason(BudgetSizeEstimate estimate) {
        return estimate == null ? null : estimate.fallbackReason();
    }

    private static boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }
}
