export const STATUS_ROUTES = [
  {
    path: '/login',
    name: 'login',
    componentKey: 'LoginView',
    meta: {
      title: '登录',
      layout: 'auth',
      public: true,
      status: 'mvp',
    },
  },
  {
    path: '/403',
    name: 'forbidden',
    componentKey: 'UnifiedErrorView',
    props: { status: 403 },
    meta: {
      title: '无权限',
      layout: 'auth',
      public: true,
      status: 'mvp',
    },
  },
  {
    path: '/404',
    name: 'not-found',
    componentKey: 'UnifiedErrorView',
    props: { status: 404 },
    meta: {
      title: '页面不存在',
      layout: 'auth',
      public: true,
      status: 'mvp',
    },
  },
  {
    path: '/500',
    name: 'server-error',
    componentKey: 'UnifiedErrorView',
    props: { status: 500 },
    meta: {
      title: '服务器错误',
      layout: 'auth',
      public: true,
      status: 'mvp',
    },
  },
]

export const APP_ROUTES = [
  {
    path: '/app',
    redirect: '/app/dashboard',
    meta: {
      hidden: true,
      status: 'mvp',
    },
  },
  {
    path: '/app/dashboard',
    name: 'dashboard',
    componentKey: 'DashboardPage',
    meta: {
      title: '工作台',
      layout: 'console',
      permissions: ['course:read'],
      status: 'mvp',
      navGroup: 'dashboard',
      section: 'dashboard',
      keepAlive: true,
    },
  },
  {
    path: '/app/system',
    name: 'system',
    redirect: '/app/health',
    meta: {
      title: '系统与审计',
      layout: 'console',
      permissions: ['system:read'],
      status: 'mvp',
      navGroup: 'system',
      section: 'settings',
    },
  },
  {
    path: '/app/health',
    name: 'health',
    componentKey: 'HealthView',
    meta: {
      title: '系统健康',
      layout: 'console',
      permissions: ['system:read'],
      status: 'mvp',
      navGroup: 'system',
      section: 'settings',
    },
  },
  {
    path: '/app/courses',
    name: 'courses',
    componentKey: 'ModulePage',
    meta: {
      title: '课程列表',
      layout: 'console',
      permissions: ['course:read'],
      status: 'mvp',
      navGroup: 'courses',
      section: 'production',
      keepAlive: true,
    },
  },
  {
    path: '/app/courses/:courseId',
    name: 'course-detail',
    componentKey: 'ModulePage',
    meta: {
      title: '课程详情',
      layout: 'detail',
      permissions: ['course:read'],
      status: 'mvp',
      navGroup: 'courses',
      section: 'production',
      resource: 'course',
      scope: 'course',
    },
  },
  {
    path: '/app/courses/:courseId/members',
    name: 'course-members',
    componentKey: 'ModulePage',
    meta: {
      title: '课程成员',
      layout: 'detail',
      permissions: ['membership:read'],
      status: 'mvp',
      navGroup: 'courses',
      section: 'production',
      resource: 'courseMembers',
      scope: 'course',
    },
  },
  {
    path: '/app/courses/:courseId/materials',
    name: 'course-materials',
    componentKey: 'ModulePage',
    meta: {
      title: '课程资料',
      layout: 'detail',
      permissions: ['material:read'],
      status: 'mvp',
      navGroup: 'courses',
      section: 'production',
      resource: 'courseMaterials',
      scope: 'course',
    },
  },
  {
    path: '/app/materials/:materialId',
    name: 'material-detail',
    componentKey: 'ModulePage',
    meta: {
      title: '资料详情',
      layout: 'detail',
      permissions: ['material:read'],
      status: 'mvp',
      navGroup: 'courses',
      section: 'production',
      resource: 'material',
      scope: 'course',
    },
  },
  {
    path: '/app/materials/:materialId/parse-results',
    name: 'parse-results',
    componentKey: 'ModulePage',
    meta: {
      title: '解析结果详情',
      layout: 'detail',
      permissions: ['material:read'],
      status: 'mvp',
      navGroup: 'courses',
      section: 'production',
      resource: 'parseResult',
      scope: 'course',
    },
  },
  {
    path: '/app/knowledge-bases',
    name: 'knowledge-bases',
    componentKey: 'ModulePage',
    meta: {
      title: '知识库列表',
      layout: 'console',
      permissions: ['kb:read'],
      status: 'mvp',
      navGroup: 'knowledge',
      section: 'production',
      keepAlive: true,
    },
  },
  {
    path: '/app/knowledge-bases/:kbId',
    name: 'knowledge-base-detail',
    componentKey: 'ModulePage',
    meta: {
      title: '知识库详情',
      layout: 'detail',
      permissions: ['kb:read'],
      status: 'mvp',
      navGroup: 'knowledge',
      section: 'production',
      resource: 'knowledgeBase',
      scope: 'course',
    },
  },
  {
    path: '/app/knowledge-bases/:kbId/build',
    name: 'knowledge-base-build',
    componentKey: 'ModulePage',
    meta: {
      title: '构建向导',
      layout: 'workflow',
      permissions: ['kb:index'],
      status: 'mvp',
      navGroup: 'knowledge',
      section: 'production',
      resource: 'knowledgeBase',
      scope: 'course',
    },
  },
  {
    path: '/app/knowledge-bases/:kbId/index-runs',
    name: 'index-runs',
    componentKey: 'RouteState',
    props: { state: 'coming-soon' },
    meta: {
      title: '索引运行列表',
      layout: 'detail',
      permissions: ['kb:read'],
      status: 'upcoming',
      routeState: 'coming-soon',
      navGroup: 'knowledge',
      section: 'production',
    },
  },
  {
    path: '/app/index-runs/:indexRunId',
    name: 'index-run-detail',
    componentKey: 'ModulePage',
    meta: {
      title: '索引运行详情',
      layout: 'detail',
      permissions: ['kb:read'],
      status: 'mvp',
      navGroup: 'knowledge',
      section: 'production',
      resource: 'indexRun',
      scope: 'course',
    },
  },
  {
    path: '/app/qa-sessions',
    name: 'qa-sessions',
    componentKey: 'ModulePage',
    meta: {
      title: '问答会话列表',
      layout: 'console',
      permissions: ['qa:read'],
      status: 'mvp',
      navGroup: 'qa',
      section: 'operations',
      keepAlive: true,
    },
  },
  {
    path: '/app/qa-sessions/:sessionId',
    name: 'qa-session-detail',
    componentKey: 'ModulePage',
    meta: {
      title: '问答会话详情',
      layout: 'detail',
      permissions: ['qa:read'],
      status: 'mvp',
      navGroup: 'qa',
      section: 'operations',
      resource: 'qaSession',
      scope: 'course',
    },
  },
  {
    path: '/app/retrieval-logs',
    name: 'retrieval-logs',
    componentKey: 'RouteState',
    props: { state: 'coming-soon' },
    meta: {
      title: '检索日志',
      layout: 'console',
      permissions: ['qa:log:read'],
      status: 'upcoming',
      routeState: 'coming-soon',
      navGroup: 'qa',
      section: 'operations',
    },
  },
  {
    path: '/app/retrieval-logs/:logId',
    name: 'retrieval-log-detail',
    componentKey: 'RouteState',
    props: { state: 'coming-soon' },
    meta: {
      title: '检索日志详情',
      layout: 'detail',
      permissions: ['qa:log:read'],
      status: 'upcoming',
      routeState: 'coming-soon',
      navGroup: 'qa',
      section: 'operations',
    },
  },
  {
    path: '/app/qa-smoke',
    name: 'qa-smoke',
    componentKey: 'RouteState',
    props: { state: 'coming-soon' },
    meta: {
      title: '知识库验证',
      layout: 'console',
      permissions: ['qa:read'],
      status: 'upcoming',
      routeState: 'coming-soon',
      navGroup: 'qa',
      section: 'operations',
    },
  },
  {
    path: '/app/users',
    name: 'users',
    componentKey: 'ModulePage',
    meta: {
      title: '用户列表',
      layout: 'console',
      permissions: ['user:read'],
      status: 'mvp',
      navGroup: 'users',
      section: 'settings',
      keepAlive: true,
    },
  },
  {
    path: '/app/users/:userId',
    name: 'user-detail',
    componentKey: 'RouteState',
    props: { state: 'coming-soon' },
    meta: {
      title: '用户详情',
      layout: 'detail',
      permissions: ['user:read'],
      status: 'upcoming',
      routeState: 'coming-soon',
      navGroup: 'users',
      section: 'settings',
    },
  },
  {
    path: '/app/roles',
    name: 'roles',
    componentKey: 'ModulePage',
    meta: {
      title: '角色列表',
      layout: 'console',
      permissions: ['role:read'],
      status: 'mvp',
      navGroup: 'users',
      section: 'settings',
    },
  },
  {
    path: '/app/permissions',
    name: 'permissions',
    componentKey: 'ModulePage',
    meta: {
      title: '权限列表',
      layout: 'console',
      permissions: ['permission:read'],
      status: 'mvp',
      navGroup: 'users',
      section: 'settings',
    },
  },
  {
    path: '/app/authorization-audit-logs',
    name: 'authorization-audit-logs',
    componentKey: 'RouteState',
    props: { state: 'coming-soon' },
    meta: {
      title: '授权审计日志',
      layout: 'console',
      permissions: ['audit:read'],
      status: 'upcoming',
      routeState: 'coming-soon',
      navGroup: 'system',
      section: 'settings',
    },
  },
]

export const routeRecords = [...STATUS_ROUTES, ...APP_ROUTES]

export const NAV_SECTIONS = [
  { key: 'dashboard', label: '' },
  { key: 'production', label: '生产' },
  { key: 'operations', label: '运维' },
  { key: 'settings', label: '设置' },
]

export const primaryNavigation = [
  { section: 'dashboard', key: 'dashboard', label: '工作台', path: '/app/dashboard', permissions: ['course:read'] },

  { section: 'production', key: 'courses', label: '课程', path: '/app/courses', permissions: ['course:read'] },
  { section: 'production', key: 'materials', label: '资料', path: '/app/materials', permissions: ['material:read'], hidden: true },
  { section: 'production', key: 'knowledge-bases', label: '知识库', path: '/app/knowledge-bases', permissions: ['kb:read'] },

  { section: 'operations', key: 'qa-sessions', label: '问答会话', path: '/app/qa-sessions', permissions: ['qa:read'] },
  { section: 'operations', key: 'retrieval-logs', label: '检索日志', path: '/app/retrieval-logs', permissions: ['qa:log:read'] },
  { section: 'operations', key: 'kb-validation', label: '知识库验证', path: '/app/qa-smoke', permissions: ['qa:read'] },

  { section: 'settings', key: 'users', label: '用户与权限', path: '/app/users', permissions: ['user:read'] },
  { section: 'settings', key: 'health', label: '系统健康', path: '/app/health', permissions: ['system:read'] },
  { section: 'settings', key: 'audit', label: '审计日志', path: '/app/authorization-audit-logs', permissions: ['audit:read'] },
]
